"use client";

import { FormEvent, useEffect, useRef, useState } from "react";
import { type DiaryEntry, type DiaryPrompt, type DiarySummary, getDiaryEntries, getDiaryPrompt, getDiarySummary, submitDiaryEntry } from "../lib/api";
import { SlovakKeyboard } from "./SlovakKeyboard";


export function DiaryScreen() {
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const [prompt, setPrompt] = useState<DiaryPrompt | null>(null); const [summary, setSummary] = useState<DiarySummary | null>(null); const [entries, setEntries] = useState<DiaryEntry[]>([]);
  const [answer, setAnswer] = useState(""); const [feedback, setFeedback] = useState<DiaryEntry | null>(null); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = async () => { setLoading(true); setError(null); try { const [nextPrompt, nextSummary, nextEntries] = await Promise.all([getDiaryPrompt(), getDiarySummary(), getDiaryEntries()]); setPrompt(nextPrompt); setSummary(nextSummary); setEntries(nextEntries); } catch (cause) { setError(cause instanceof Error ? cause.message : "Не удалось загрузить дневник."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const insertKey = (key: string) => { const textarea = textareaRef.current; if (!textarea) return; const start = textarea.selectionStart ?? answer.length; const end = textarea.selectionEnd ?? start; setAnswer(`${answer.slice(0, start)}${key}${answer.slice(end)}`); requestAnimationFrame(() => { textarea.focus(); textarea.setSelectionRange(start + key.length, start + key.length); }); };
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!prompt || !answer.trim() || submitting) return; setSubmitting(true); setError(null); try { const entry = await submitDiaryEntry(prompt, answer); setFeedback(entry); setAnswer(""); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Не удалось проверить запись."); } finally { setSubmitting(false); } };
  return <section className="native-diary" aria-labelledby="diary-title"><div className="native-exercises-heading"><div><p className="native-eyebrow">Практика письма</p><h2 id="diary-title">AI-дневник</h2><p>Короткая запись на словацком с проверкой и сохранением прогресса.</p></div><button className="native-refresh" type="button" onClick={() => void load()} disabled={loading}>Обновить</button></div>{error && <p className="native-notice error" role="alert">{error}</p>}{loading && <p className="native-notice">Загружаю дневник…</p>}{!loading && prompt && <><section className="native-diary-prompt"><strong>Вопрос дня</strong><p>{prompt.prompt}{prompt.has_entry_today && " Запись за сегодня уже сохранена, можно добавить ещё одну."}</p></section>{summary && <><div className="native-diary-summary"><span>За 7 дней: <b>{summary.entries_count}</b> записей</span><span>Средний балл: <b>{summary.average_score ?? "—"}</b></span><span>Новых слов: <b>{summary.new_words_count}</b></span></div></>}<form className="native-diary-form" onSubmit={(event) => void submit(event)}><textarea ref={textareaRef} rows={6} value={answer} onChange={(event) => setAnswer(event.target.value)} placeholder="Напиши несколько предложений по-словацки…" disabled={submitting} required /><SlovakKeyboard onInsert={insertKey} disabled={submitting} /><button className="native-submit-answer" type="submit" disabled={!answer.trim() || submitting}>{submitting ? "AI проверяет…" : "Проверить запись"}</button></form>{feedback && <article className={`native-diary-feedback ${feedback.is_correct ? "correct" : "wrong"}`}><strong>{feedback.is_correct ? "Запись принята" : "Есть что исправить"} · {feedback.score}/100</strong><p><b>Исправленный вариант:</b> {feedback.corrected_text}</p><p>{feedback.explanation}</p></article>}<section className="native-diary-history"><h3>Последние записи</h3>{entries.length ? entries.slice(0, 3).map((entry) => <article key={entry.id}><strong>{entry.score}/100</strong><p>{entry.corrected_text}</p><small>{entry.explanation}</small></article>) : <p className="native-notice">История дневника пока пуста.</p>}</section></>}</section>;
}
