"use client";

import { FormEvent, useEffect, useRef, useState } from "react";
import { type Assessment, type Homework, type LessonOption, generateHomework, getExerciseTopics, getHomework, submitHomework } from "../lib/api";
import { SlovakKeyboard } from "./SlovakKeyboard";


function parseAssessment(item: Homework): Assessment | null {
  try { return item.ai_feedback ? JSON.parse(item.ai_feedback) as Assessment : null; } catch { return null; }
}

function HomeworkCard({ item, onSubmitted }: { item: Homework; onSubmitted: () => Promise<void> }) {
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const [answer, setAnswer] = useState(""); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState<string | null>(null); const [result, setResult] = useState<Assessment | null>(parseAssessment(item)); const [isOpen, setIsOpen] = useState(false);
  const needsCorrection = item.mistake_id !== null;
  const canSubmit = item.score === null || needsCorrection;
  const openStateKey = `homework_card_open_${item.id}`;
  useEffect(() => { setIsOpen(window.localStorage.getItem(openStateKey) === "true"); }, [openStateKey]);
  const updateOpenState = (open: boolean) => { setIsOpen(open); window.localStorage.setItem(openStateKey, String(open)); };
  const insertKey = (key: string) => { const textarea = textareaRef.current; if (!textarea) return; const start = textarea.selectionStart ?? answer.length; const end = textarea.selectionEnd ?? start; setAnswer(`${answer.slice(0, start)}${key}${answer.slice(end)}`); requestAnimationFrame(() => { textarea.focus(); textarea.setSelectionRange(start + key.length, start + key.length); }); };
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!answer.trim() || submitting) return; setSubmitting(true); setError(null); try { const response = await submitHomework(item.id, answer); setResult(response.assessment); setAnswer(""); await onSubmitted(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Не удалось проверить домашнее задание."); } finally { setSubmitting(false); } };
  return <details className="native-homework-card" open={isOpen} onToggle={(event) => updateOpenState(event.currentTarget.open)}><summary className="native-homework-card-heading"><div><strong>{item.title}</strong>{item.focus_category && <small>Фокус: {item.focus_category}</small>}</div><div className="native-homework-card-meta"><span>{canSubmit ? "Открыть и выполнить" : "Просмотреть разбор"}</span>{item.score !== null && <span>{item.score}/100</span>}</div></summary><div className="native-homework-card-content"><p className="native-homework-description">{item.description}</p>{result && <section className={`native-homework-feedback ${result.is_correct ? "correct" : "wrong"}`}><div><strong>{result.is_correct ? "Выполнено правильно" : "Разбор ошибок"}</strong><span>{result.score}/100</span></div>{item.submitted_answer && <p><b>Твой ответ</b>{item.submitted_answer}</p>}<p><b>Исправленный вариант</b>{result.corrected_answer}</p><p><b>Объяснение</b>{result.explanation}</p><p className="next"><b>Что повторить</b>{result.next_exercise}</p></section>}{canSubmit && <form className="native-homework-form" onSubmit={(event) => void submit(event)}><textarea ref={textareaRef} rows={5} value={answer} onChange={(event) => setAnswer(event.target.value)} placeholder="Выполни задание здесь…" disabled={submitting} required /><SlovakKeyboard onInsert={insertKey} disabled={submitting} /><button className="native-submit-answer" type="submit" disabled={!answer.trim() || submitting}>{submitting ? "AI проверяет…" : needsCorrection ? "Отправить исправление" : "Отправить на проверку"}</button>{error && <p className="native-notice error" role="alert">{error}</p>}</form>}</div></details>;
}

export function HomeworkScreen() {
  const [items, setItems] = useState<Homework[]>([]); const [topics, setTopics] = useState<LessonOption[]>([]); const [lessonId, setLessonId] = useState<number | null>(null); const [loading, setLoading] = useState(true); const [generating, setGenerating] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = async () => { setLoading(true); setError(null); try { const [nextItems, nextTopics] = await Promise.all([getHomework(), getExerciseTopics()]); setItems(nextItems); setTopics(nextTopics); setLessonId((current) => current ?? nextTopics.find((topic) => topic.status === "current")?.id ?? nextTopics[0]?.id ?? null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Не удалось загрузить домашние задания."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const generate = async () => { if (!lessonId || generating) return; setGenerating(true); setError(null); try { await generateHomework(lessonId); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Не удалось создать домашнее задание."); } finally { setGenerating(false); } };
  return <section className="native-homework" aria-labelledby="homework-title"><div className="native-exercises-heading"><div><p className="native-eyebrow">Самостоятельная практика</p><h2 id="homework-title">Домашние задания</h2><p>AI создаёт задание по выбранной теме, проверяет ответ и сохраняет разбор.</p></div><button className="native-refresh" type="button" onClick={() => void load()} disabled={loading}>Обновить</button></div>{error && <p className="native-notice error" role="alert">{error}</p>}{loading && <p className="native-notice">Загружаю домашние задания…</p>}{!loading && <><section className="native-homework-create"><label>Тема для нового задания<select value={lessonId ?? ""} onChange={(event) => setLessonId(Number(event.target.value))}>{topics.map((topic) => <option key={topic.id} value={topic.id}>{topic.title} · {topic.status === "completed" ? "выполнено" : topic.status === "current" ? "текущая" : "впереди"}</option>)}</select></label><button className="native-download" type="button" onClick={() => void generate()} disabled={!lessonId || generating}>{generating ? "AI создаёт…" : "Создать задание"}</button></section><section className="native-homework-list">{items.length ? items.slice(0, 3).map((item) => <HomeworkCard key={item.id} item={item} onSubmitted={load} />) : <p className="native-notice">Домашнее задание появится после сохранения темы или его можно создать здесь.</p>}</section></>}</section>;
}
